name: gh-pages-deployment
on:
  push:
    branches:
      - source
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.75.1'

      - name: Build Site
        run: hugo

      - name: Build site with Hugo
        run: hugo

      - name: Run Build Script
        run: |
          chmod -R +x ./.github/scripts/
          ./.github/scripts/build-site.sh
        shell: bash
        env:
          TARGET_BRANCH: main
